//
// Given two strings s and t which consist of only lowercase letters.
//
//     String t is generated by random shuffling string s and then add one more letter at a random position.
//
//     Find the letter that was added in t.
//
//     Example:
//
// Input:
//     s = "abcd"
// t = "abcde"
//
// Output:
//     e
//
// Explanation:
//     'e' is the letter that was added.




/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    s = s.split('').sort()
    t = t.split('').sort()

    for(i = 0; i < t.length; i++){
        if(s[i] !== t[i]){
            return t[i]
        }
    }

};

console.log(findTheDifference("abcd", "abcde"))
